### DISCUSSION TITLE
Neeva

### DISCUSSION THREAD

**Discussion by SaschaU** [linuxserver/Heimdall#1016] [Search Providers]
```
Neeva:
   id: Neeva
   url: https://www.neeva.com/search
   name: Neeva
   method: get
   target: _blank
   query: q
```
