### DISCUSSION TITLE
Ecosia

### DISCUSSION THREAD

**Discussion by pmcelreavy** [linuxserver/Heimdall#1033] [Search Providers]
```
ecosia:
   id: ecosia
   url: https://www.ecosia.org/search
   name: Ecosia
   method: get
   target: _blank
   query: q
```
