### DISCUSSION TITLE
whoogle

### DISCUSSION THREAD

**Discussion by obito26m** [linuxserver/Heimdall#1122] [Search Providers]
```
whoogle:
   id: whoogle
   url: https://yourdomain/search
   name: Whoogle
   method: get
   target: _blank
   query: q
```
