### DISCUSSION TITLE
talosintelligence

### DISCUSSION THREAD

**Discussion by mrlnbllmnn** [linuxserver/Heimdall#1207] [Search Providers]
```
talosintelligence:
   id: talosintelligence
   url: https://talosintelligence.com/reputation_center/lookup
   name: Talos Intelligence
   method: get
   target: _blank
   query: search
```
