### DISCUSSION TITLE
Hurricane Electric BGP Toolkit

### DISCUSSION THREAD

**Discussion by mrlnbllmnn** [linuxserver/Heimdall#1208] [Search Providers]
```
hebgptool:
   id: hebgptool
   url: https://bgp.he.net/search
   name: HE BGP Toolkit
   method: get
   target: _blank
   query: search%5Bsearch%5D
```
