### DISCUSSION TITLE
Reddit Search

### DISCUSSION THREAD

**Discussion by mrlnbllmnn** [linuxserver/Heimdall#1209] [Search Providers]
```
reddit:
   id: reddit
   url: https://www.reddit.com/search/
   name: Reddit Search
   method: get
   target: _blank
   query: q
```
