### DISCUSSION TITLE
Facebook Search

### DISCUSSION THREAD

**Discussion by mrlnbllmnn** [linuxserver/Heimdall#1210] [Search Providers]
```
facebook: 
   id: facebook
   url: https://www.facebook.com/search/top
   name: Facebook Search
   method: get
   target: _blank
   query: q
```
