### DISCUSSION TITLE
Youtube

### DISCUSSION THREAD

**Discussion by willart7401** [linuxserver/Heimdall#1211] [Search Providers]
```
youtube: 
   id: youtube
   url: https://www.youtube.com/results
   name: Youtube
   method: get
   target: _blank
   query: search_query
```
