### DISCUSSION TITLE
TMDB

### DISCUSSION THREAD

**Discussion by willart7401** [linuxserver/Heimdall#1212] [Search Providers]
```
tmdb:
   id: tmdb
   url: https://www.themoviedb.org/search
   name: TMDB
   method: get
   target: _blank
   query: query
```
