### DISCUSSION TITLE
Heise Downloads

### DISCUSSION THREAD

**Discussion by chrisschm** [linuxserver/Heimdall#1314] [Search Providers]
```
heisedl:
   id: heisedl
   url: https://www.heise.de/download/search
   name: Heise Downloads
   method: get
   target: _blank
   query: terms
```
