### DISCUSSION TITLE
Heise Preisvergleich

### DISCUSSION THREAD

**Discussion by chrisschm** [linuxserver/Heimdall#1315] [Search Providers]
```
heisepreise:
   id: heisepreise
   url: https://www.heise.de/preisvergleich/
   name: Heise Preisvergleich
   method: get
   target: _blank
   query: fs
```
