### DISCUSSION TITLE
Metacrawler

### DISCUSSION THREAD

**Discussion by chrisschm** [linuxserver/Heimdall#1316] [Search Providers]
```
metacrawler:
   id: metacrawler
   url: https://www.metacrawler.com/serp
   name: Metacrawler
   method: get
   target: _blank
   query: q
```
