### DISCUSSION TITLE
metaGer

### DISCUSSION THREAD

**Discussion by chrisschm** [linuxserver/Heimdall#1317] [Search Providers]
```
metager:
   id: metager
   url: https://metager.de/meta/meta.ger3
   name: metaGer
   method: get
   target: _blank
   query: eingabe
```
