### DISCUSSION TITLE
Kagi

### DISCUSSION THREAD

**Discussion by pbronez** [linuxserver/Heimdall#1341] [Search Providers]
```
kagi:
   id: kagi
   url: https://kagi.com/search
   name: Kagi
   method: get
   target: _blank
   query: q
```

As suggested in #1313
