### DISCUSSION TITLE
SepiaSearch

### DISCUSSION THREAD

**Discussion by MickGe** [linuxserver/Heimdall#1394] [Search Providers]
```yaml
sepiasearch:
   id: sepiasearch
   url: https://sepiasearch.org/search
   name: SepiaSearch
   method: get
   target: _blank
   query: search
```
