### DISCUSSION TITLE
Qwant

### DISCUSSION THREAD

**Discussion by KodeStar** [linuxserver/Heimdall#758] [Search Providers]
```
qwant:
   id: qwant
   url: https://www.qwant.com/
   name: Qwant
   method: get
   target: _blank
   query: q
   ```
