### DISCUSSION TITLE
Swiggle

### DISCUSSION THREAD

**Discussion by KodeStar** [linuxserver/Heimdall#759] [Search Providers]
```
swiggle:
   id: swiggle
   url: https://swiggle.org.uk/
   name: Swiggle
   method: get
   target: _blank
   query: q
```
