### DISCUSSION TITLE
Yandex

### DISCUSSION THREAD

**Discussion by KodeStar** [linuxserver/Heimdall#760] [Search Providers]
```
yandex:
   id: yandex
   url: https://yandex.com/search/
   name: Yandex
   method: get
   target: _blank
   query: text
```
