### DISCUSSION TITLE
Baidu

### DISCUSSION THREAD

**Discussion by KodeStar** [linuxserver/Heimdall#761] [Search Providers]
```
baidu:
   id: baidu
   url: https://www.baidu.com/s
   name: Baidu
   method: get
   target: _blank
   query: wd
   ```
