### DISCUSSION TITLE
css help and documentation

### DISCUSSION THREAD

**Discussion by hackitz** [linuxserver/Heimdall#788] [Ideas]
hey all,
so i've been playing with css, what i cant figure out is how to change the search box. is there an example for this?
maybe someone can add a basic css for themes, i've searched and found nothing for the search box, i did find a bit about the rest of the page.
here is where i'm at.
`@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@500:600&display=swap');

#app {
  background-position: right;
}
#app #sortable,
#app main {
  padding: 10px;
}
#config-buttons {
  bottom: 50%;
  transform: translateY(50%);
  border-top-left-radius: 10px;
  border-bottom-left-radius: 10px;
  box-shadow: rgba(255, 255, 255, 0.1) -1px 1px 1px 0, rgba(255, 255, 255, 0.1) 0 -1px 1px 0,
    rgba(0, 0, 0, 0.1) -1px 0 20px 5px;
  background-color: rgba(40, 40, 40, 0.25);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
}
#config-buttons a {
  background: none;
}
#config-buttons a svg {
  transition: all 0.1s ease-in-out;
  color: rgba(255, 255, 255, 0.5);
}
#config-buttons a:hover svg {
  transform: scale(1.1);
  color: rgba(6, 105, 205, 0.95);
}

.black {
  color: white !important;
}

.item {
  box-shadow: rgba(0, 0, 0, 0.05) -1px -1px 5px 0, rgba(0, 0, 0, 0.15) 0px 20px 25px -5px,
    rgba(0, 0, 0, 0.04) 0px 10px 10px -5px !important;
  border-radius: 25% 10%;
  background-image: none;
  border: none;
  outline: thick double #066acf;
  height: 70px;
  width: 240px;
  margin: 1.25rem;
  padding: 1rem 55px 1rem 1rem;
  transition: all 0.25s ease-in-out;
  transition-property: transform, box-shadow, background-color;
  background-color: rgba(14, 26, 38, 0.9) !important;
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
}
.item:after {
  height: 70px;
  opacity: 0.2;
}
.item:hover {
  transform: scale(1.1);
  background-color: rgba(100, 175, 250, 0.2) !important;
  box-shadow: rgba(0, 0, 0, 0.1) 0px 60px 40px -7px !important;
}
.item .svg-inline--fa {
  height: 70px;
  vertical-align: middle;
  opacity: 0.2;
}

@media only screen and (max-width: 750px) {
  .item {
    padding-top: 2rem;
    padding-bottom: 2rem;
  }
  #config-buttons {
    display: none;
  }
}

.details * {
  color: white !important;
}
.details {
  padding: 0 0.5rem;
}

.app-icon {
  width: 42px !important;
  height: 42px !important;
  filter: drop-shadow(1px 1px 2px rgba(10, 0, 20, 0.1));
}

.livestats-container {
  margin-top: 0.5rem;
}
.livestats-container .livestats .title {
  margin-bottom: 2px;
}
.livestats-container .livestats li {
  padding-right: 1rem;
}

.livestats-container strong {
  font-weight: 300 !important;
  padding: 0 2px;
}

.details > .title {
  font-weight: 400;
  font-size: 1.2rem !important;
  letter-spacing: 1px;
  font-family: "Orbitron", sans-serif;
  text-shadow: rgba(10, 0, 60, 0.25) 1px 0 5px;
  text-shadow: -1px -1px 1px rgba(255, 255, 255, 0.1), 1px 1px 2px rgba(10, 0, 60, 0.25);
  transition: all 0.25s ease-in-out;
}
.item:hover .details > .title {
  text-shadow: -1px -1px 1px rgba(100,175, 250, 0.1), 1px 1px 5px rgba(10, 0, 60, 0.2);`

**Comment by hackitz** [comment]
sorted it out, heres my new css theme:

@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@500:600&display=swap');
.searchform {
  margin: 20px auto;
  padding: 2px;
  border-radius: 4px;
  width: 80%;
  max-width: 620px;
}
.searchform .input-container {
  background: #caebf2;
  border-radius: 5px;
  box-shadow: 0px 0px 5px 0 rgba(0, 0, 0, 0.4);
  overflow: hidden;
  position: relative;
  display: flex;
}
.searchform button {
  position: absolute;
  right: 0px;
  top: 0px;
  border: none;
  font-size: 16px;
  padding: 7px 8px;
  line-height: 38px;
  font-weight: 500;
  border-top-right-radius: 5px;
  border-bottom-right-radius: 5px;
  color: black;
  text-transform: uppercase;
  background: #3f74d9;
}
#app {
  background-position: right;
}
#app #sortable,
#app main {
  padding: 8px;
}
#config-buttons {
  bottom: 50%;
  transform: translateY(50%);
  border-top-left-radius: 15px;
  border-bottom-left-radius: 15px;
  box-shadow: rgba(255, 255, 255, 0.1) -1px 1px 1px 0, rgba(255, 255, 255, 0.1) 0 -1px 1px 0,
    rgba(0, 0, 0, 0.1) -1px 0 20px 5px;
  background-color: rgba(40, 40, 40, 0.25);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
}
#config-buttons a {
  background: none;
}
#config-buttons a svg {
  transition: all 0.1s ease-in-out;
  color: rgba(255, 255, 255, 0.5);
}
#config-buttons a:hover svg {
  transform: scale(1.1);
  color: rgba(6, 105, 205, 0.95);
}

.black {
  color: white !important;
}

.item {
  box-shadow: rgba(0, 0, 0, 0.05) -1px -1px 5px 0, rgba(0, 0, 0, 0.15) 0px 20px 25px -5px,
    rgba(0, 0, 0, 0.04) 0px 10px 10px -5px !important;
  border-radius: 4% 4%;
  background-image: none;
  border:1px solid rgba(6, 105, 205, 0.45);
  outline: none;
  height: 70px;
  width: 260px;
  margin: 0.6rem;
  padding: .5rem 5px .5rem .5rem;
  transition: all 0.25s ease-in-out;
  transition-property: transform, box-shadow, background-color;
  background-color: rgba(14, 26, 38, 0.9) !important;
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
}
.item:after {
  height: 70px;
  opacity: 0.2;
}
.item:hover {
  transform: scale(1.1);
  background-color: rgba(100, 175, 250, 0.2) !important;
  box-shadow: rgba(0, 0, 0, 0.1) 0px 60px 40px -7px !important;
}
.item .svg-inline--fa {
  height: 30px;
  vertical-align: middle;
  opacity: 0.2;
  width: .675em;
  line-height: 110px;
}
.item .link {
  line-height: 110px;
}
@media only screen and (max-width: 750px) {
  .item {
    padding-top: 2rem;
    padding-bottom: 2rem;
  }
  #config-buttons {
    display: none;
  }
}

.details * {
  color: white !important;
}
.details {
  padding: 0 0.5rem;
}

.app-icon {
  width: 42px !important;
  height: 42px !important;
  filter: drop-shadow(1px 1px 2px rgba(10, 0, 20, 0.1));
}

element {

}
.app-icon-container {
    width: 60px;
    height: 60px;
    display: flex;
    justify-content: center;
    align-items: center;
    margin-right: 5px;
    flex: 0 0 50px;
}
.livestats-container {
  margin-top: 0.5rem;
}
.livestats-container .livestats .title {
  margin-bottom: 2px;
}
.livestats-container .livestats li {
  padding-right: 1rem;
}

.livestats-container strong {
  font-weight: 275 !important;
  padding: 0 2px;
}

.details > .title {
  font-weight: 375;
  font-size: 1.1rem !important;
  letter-spacing: 1px;
  font-family: "Orbitron", sans-serif;
  text-shadow: rgba(10, 0, 60, 0.25) 1px 0 5px;
  text-shadow: -1px -1px 1px rgba(255, 255, 255, 0.1), 1px 1px 2px rgba(10, 0, 60, 0.25);
  transition: all 0.25s ease-in-out;
}
.item:hover .details > .title {
  text-shadow: -1px -1px 1px rgba(100,175, 250, 0.1), 1px 1px 5px rgba(10, 0, 60, 0.2);
}

**Reply by hackitz** [reply]
updated as google fonts url changed.
----------------------------------------------------------
@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@500&display=swap');
.searchform {
  margin: 5px auto;
  padding: 2px;
  border-radius: 2px;
  width: 80%;
  max-width: 620px;
  height: 32px;
}
.searchform form {
  width: 100%;
  height: 32px;
}
.searchform .input-container {
  background: #caebf2;
  border-radius: 3px;
  box-shadow: 0px 0px 5px 0 rgba(0, 0, 0, 0.4);
  height: 32px;
  font-size: 12px;
  font-weight: 300;
  overflow: hidden;
  position: relative;
  display: flex;
}
.searchform input {
  padding: 1px 4px;
  font-size: 12px;
  border: 0 none;
  width: 100%;
  background: transparent;
}
.homesearch {
  height: 32px;
}
.searchform button {
  position: absolute;
  right: 0px;
  top: 0px;
  border: none;
  font-size: 12px;
  text-align: center;
  padding: 1px 4px;
  line-height: 32px;
  font-weight: 300;
  border-top-right-radius: 3px;
  border-bottom-right-radius: 3px;
  color: black;
  text-transform: uppercase;
  background: #3f74d9;
}
#app {
  background-position: right;
}
#app #sortable,
#app main {
  padding: 8px;
}
#config-buttons {
  bottom: 50%;
  transform: translateY(50%);
  border-top-left-radius: 15px;
  border-bottom-left-radius: 15px;
  box-shadow: rgba(255, 255, 255, 0.1) -1px 1px 1px 0, rgba(255, 255, 255, 0.1) 0 -1px 1px 0,
    rgba(0, 0, 0, 0.1) -1px 0 20px 5px;
  background-color: rgba(40, 40, 40, 0.25);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
}
#config-buttons a {
  background: none;
}
#config-buttons a svg {
  transition: all 0.1s ease-in-out;
  color: rgba(255, 255, 255, 0.5);
}
#config-buttons a:hover svg {
  transform: scale(1.1);
  color: rgba(6, 105, 205, 0.95);
}

.black {
  color: white !important;
}

.item {
  box-shadow: rgba(0, 0, 0, 0.05) -1px -1px 5px 0, rgba(0, 0, 0, 0.15) 0px 20px 25px -5px,
    rgba(0, 0, 0, 0.04) 0px 10px 10px -5px !important;
  border-radius: 4% 4%;
  background-image: none;
  border:1px solid rgba(6, 105, 205, 0.45);
  outline: none;
  height: 70px;
  width: 250px;
  margin: 0.6rem;
  padding: .5rem 5px .5rem .5rem;
  transition: all 0.25s ease-in-out;
  transition-property: transform, box-shadow, background-color;
  background-color: rgba(14, 26, 38, 0.9) !important;
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
}
.item:after {
  height: 70px;
  opacity: 0.2;
}
.item:hover {
  transform: scale(1.1);
  background-color: rgba(100, 175, 250, 0.2) !important;
  box-shadow: rgba(0, 0, 0, 0.1) 0px 30px 20px -7px !important;
}
.item .svg-inline--fa {
  height: 30px;
  vertical-align: middle;
  opacity: 0.2;
  width: .675em;
  line-height: 110px;
}
.item .link {
  line-height: 110px;
}
@media only screen and (max-width: 750px) {
  .item {
    padding-top: 2rem;
    padding-bottom: 2rem;
  }
  #config-buttons {
    display: none;
  }
}

.details * {
  color: white !important;
}
.details {
  padding: 0 0.5rem;
}

.app-icon {
  width: 42px !important;
  height: 42px !important;
  filter: drop-shadow(1px 1px 2px rgba(10, 0, 20, 0.1));
}

element {

}
.app-icon-container {
    width: 60px;
    height: 60px;
    display: flex;
    justify-content: center;
    align-items: center;
    margin-right: 5px;
    flex: 0 0 50px;
}
.livestats-container {
  margin-top: 0.5rem;
}
.livestats-container .livestats .title {
  margin-bottom: 2px;
}
.livestats-container .livestats li {
  padding-right: 1rem;
}

.livestats-container strong {
  font-weight: 275 !important;
  padding: 0 2px;
}

.details > .title {
  font-weight: 375;
  font-size: 1.1em !important;
  letter-spacing: 1px;
  font-family: "Orbitron", sans-serif;
  text-shadow: rgba(10, 0, 60, 0.25) 1px 0 5px;
  text-shadow: -1px -1px 1px rgba(255, 255, 255, 0.1), 1px 1px 2px rgba(10, 0, 60, 0.25);
  transition: all 0.25s ease-in-out;
}
.item:hover .details > .title {
  text-shadow: -1px -1px 1px rgba(100,175, 250, 0.1), 1px 1px 5px rgba(10, 0, 60, 0.2);
}

**Comment by stevietv** [comment]
thanks for this, i love it!

**Comment by sunteta** [comment]
I modified it a little bit and it looked better,sheare~~~  have fun...
use this wallpaper Looks absolutely beautiful
https://www.artstation.com/artwork/L8gx0


```css
@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@500:600&display=swap');
.searchform {
margin: 20px auto;
padding: 2px;
border-radius: 4px;
width: 80%;
max-width: 620px;
}
.searchform .input-container {
background: #ffffff;
border-radius: 5px;
box-shadow: 0px 0px 0px 0 rgba(0, 0, 0, 0.4);
overflow: hidden;
position: relative;
display: flex;
}
.searchform button {
position: absolute;
right: 0px;
top: 0px;
border: none;
font-size: 16px;
padding: 7px 8px;
line-height: 38px;
font-weight: 500;
border-top-right-radius: 5px;
border-bottom-right-radius: 5px;
color: #ffffff;
text-transform: uppercase;
background: #2d4980;
}
#app {
background-position: right;
}
#app #sortable,
#app main {
padding: 8px;
}
#config-buttons {
bottom: 50%;
transform: translateY(50%);
border-top-left-radius: 15px;
border-bottom-left-radius: 15px;
box-shadow: rgba(255, 255, 255, 0.1) -1px 1px 1px 0, rgba(255, 255, 255, 0.1) 0 -1px 1px 0,
rgba(0, 0, 0, 0.1) -1px 0 20px 5px;
background-color: rgba(40, 40, 40, 0.25);
backdrop-filter: blur(10px);
-webkit-backdrop-filter: blur(10px);
}
#config-buttons a {
background: none;
}
#config-buttons a svg {
transition: all 0.1s ease-in-out;
color: rgba(255, 255, 255, 0.5);
}
#config-buttons a:hover svg {
transform: scale(1.1);
color: rgba(6, 105, 205, 0.95);
}

.black {
color: white !important;
}

.item {
box-shadow: rgba(0, 0, 0, 0.05) -1px -1px 5px 0, rgba(0, 0, 0, 0.15) 0px 20px 25px -5px,
rgba(0, 0, 0, 0.04) 0px 10px 10px -5px !important;
border-radius: 4% 4%;
background-image: none;
border:1px solid rgba(6, 105, 205, 0.45);
outline: none;
height: 75px;
width: 260px;
margin: 0.6rem;
padding: .5rem 5px .5rem .5rem;
transition: all 0.25s ease-in-out;
transition-property: transform, box-shadow, background-color;
background-color: rgba(14, 26, 38, 0.9) !important;
backdrop-filter: blur(10px);
-webkit-backdrop-filter: blur(10px);
}
.item:after {
height: 75px;
opacity: 0.3;
}
.item:hover {
transform: scale(1.1);
background-color: rgba(100, 175, 250, 0.2) !important;
box-shadow: rgba(0, 0, 0, 0.1) 0px 60px 40px -7px !important;
}
.item .svg-inline--fa {
height: 30px;
vertical-align: middle;
opacity: 0.3;
width: .675em;
line-height: 110px;
}
.item .link {
line-height: 110px;
}
@media only screen and (max-width: 750px) {
.item {
padding-top: 2rem;
padding-bottom: 2rem;
}
#config-buttons {
display: none;
}
}

.details * {
color: white !important;
}
.details {
padding: 0 0.5rem;
}

.app-icon {
width: 42px !important;
height: 42px !important;
filter: drop-shadow(1px 1px 2px rgba(10, 0, 20, 0.1));
}

element {

}
.app-icon-container {
width: 60px;
height: 60px;
display: flex;
justify-content: center;
align-items: center;
margin-right: 5px;
flex: 0 0 50px;
}
.livestats-container {
margin-top: 0.5rem;
}
.livestats-container .livestats .title {
margin-bottom: 2px;
}
.livestats-container .livestats li {
padding-right: 1rem;
}

.livestats-container strong {
font-weight: 275 !important;
padding: 0 2px;
}

.details > .title {
font-weight: 375;
font-size: 1 rem !important;
letter-spacing: 1px;
font-family: "Orbitron", sans-serif;
text-shadow: rgba(10, 0, 60, 0.25) 1px 0 5px;
text-shadow: -1px -1px 1px rgba(255, 255, 255, 0.1), 1px 1px 2px rgba(10, 0, 60, 0.25);
transition: all 0.25s ease-in-out;
}
.item:hover .details > .title {
text-shadow: -1px -1px 1px rgba(100,175, 250, 0.1), 1px 1px 5px rgba(10, 0, 60, 0.2);
}
```
