### DISCUSSION TITLE
Bing

### DISCUSSION THREAD

**Discussion by KodeStar** [linuxserver/Heimdall#802] [Search Providers]
```
bing:
   id: bing
   url: https://www.bing.com/search
   name: Bing
   method: get
   target: _blank
   query: q
   ```
