### DISCUSSION TITLE
Duck Duck Go

### DISCUSSION THREAD

**Discussion by KodeStar** [linuxserver/Heimdall#803] [Search Providers]
```
ddg:
   id: ddg
   url: https://duckduckgo.com/
   name: DuckDuckGo
   method: get
   target: _blank
   query: q
   ```
