### DISCUSSION TITLE
Google

### DISCUSSION THREAD

**Discussion by KodeStar** [linuxserver/Heimdall#804] [Search Providers]
```
google:
   id: google
   url: https://www.google.com/search
   name: Google
   method: get
   target: _blank
   query: q
```
