### DISCUSSION TITLE
Startpage

### DISCUSSION THREAD

**Discussion by KodeStar** [linuxserver/Heimdall#805] [Search Providers]
```
startpage:
   id: startpage
   url: https://www.startpage.com/do/dsearch
   name: Startpage
   method: get
   target: _blank
   query: query
```
