### DISCUSSION TITLE
Tiles

### DISCUSSION THREAD

**Discussion by KodeStar** [linuxserver/Heimdall#806] [Search Providers]
```
tiles:
   id: tiles
   name: Tiles
   target: _blank
```

This is different to the other search providers in that it searches your dashboard for matching tiles
