### DISCUSSION TITLE
Brave

### DISCUSSION THREAD

**Discussion by GrandVizierOlaf** [linuxserver/Heimdall#834] [Search Providers]
```
brave:
   id: brave
   url: https://search.brave.com/search
   name: Brave
   method: get
   target: _blank
   query: q
```
