### DISCUSSION TITLE
Presearch

### DISCUSSION THREAD

**Discussion by T3lm3** [linuxserver/Heimdall#865] [Search Providers]
```
presearch:
   id: presearch
   url: https://presearch.com/search
   name: Presearch
   method: get
   target: _blank
   query: q
```
