### DISCUSSION TITLE
Wikipedia

### DISCUSSION THREAD

**Discussion by Salan54** [linuxserver/Heimdall#887] [Search Providers]
```
wikipedia:
   id: wikipedia
   url: https://en.wikipedia.org/w/index.php
   name: Wikipedia
   method: get
   target: _blank
   query: search

```
You have to change 'en' to the language you want :
e.g :    url: https://fr.wikipedia.org/w/index.php
to search on the French wikipedia.
