### DISCUSSION TITLE
IMDB

### DISCUSSION THREAD

**Discussion by Anyndil** [linuxserver/Heimdall#914] [Search Providers]
```
imdb:
   id: imdb
   url: https://www.imdb.com/find
   name: IMDB
   method: get
   target: _blank
   query: q
```
