### DISCUSSION TITLE
Wolfram Alpha

### DISCUSSION THREAD

**Discussion by Anyndil** [linuxserver/Heimdall#915] [Search Providers]
```
wolframalpha:
   id: wolframalpha
   url: https://www.wolframalpha.com/input
   name: Wolfram Alpha
   method: get
   target: _blank
   query: i
```
