### ISSUE TITLE
500 Bad Gateway error

### ISSUE THREAD

**Issue by HesselTjeerdsma** [linuxserver/Heimdall#236]
I am trying to setup Heimdall with docker-compose and Traefik, but I cannot get it to work. I tried changing the ownership of the data dir (`$BASE_DIR`) and adjusting to PUID and PGID accordingly and using the image without traefik. I can see that the config file can be accessed in the container, but that it is not copied to the nginx.conf in the container. Could somebody please help me? 

)
```
heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    volumes:
      - ${BASE_DIR}/heimdall/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    labels:
      - traefik.backend=heimdall
      - traefik.frontend.rule=Host:heimdall.${DOMAIN}
      - traefik.docker.network=proxied
      - traefik.port=443
      - traefik.protocol=https
    networks:
      - internal
      - proxied
    expose:
      - 80
      - 443
    restart: always

```
