### ISSUE TITLE
Can't save any settings since today's version

### ISSUE THREAD

**Issue by ovizii** [linuxserver/Heimdall#245]
Here is what worked for me so far: 

`docker run -d --name=portal \
-v /home/ovi/docker/heimdall/config:/config \
--expose 80 \
--expose 443 \
--restart unless-stopped \
-e TZ=Europe/Berlin \
--label traefik.port=80 \
--label traefik.frontend.rule=Host:portal.mydomain.tld \
--label traefik.backend=portal \
--label traefik.enable=true \
linuxserver/heimdall
`

today I wanted to add authentication (via the front-end proxy traefik) and updated heimdall to the latest image which seems to have switched to alpine today. Here is my new run script: 

`docker run -d --name=portal \
-v /home/ovi/docker/heimdall/config:/config \
--expose 80 \
--expose 443 \
--restart unless-stopped \
-e TZ=Europe/Berlin \
--label traefik.port=80 \
--label traefik.frontend.rule=Host:portal.mydomain.tld \
--label traefik.backend=portal \
--label traefik.enable=true \
--label 'traefik.frontend.auth.basic=ovi:$apr1$MYPASSWORD/G5iDso0' \
linuxserver/heimdall
`

The problem now is that I can't add any bookmarks or change any settings it looks like everything is read only :-(

I checked the heimdall documentation and added: 

`-e PGID=911 \
-e PUID=911 \`

since the folder which contains the data which has worked until my fiddling today looks like this: 

`ls -al config/
total 28
drwxr-xr-x 7  911  911 4096 Jul 18 12:35 .
drwxr-xr-x 3 root root 4096 Sep  6 11:30 ..
drwxr-xr-x 2  911  911 4096 Jul 18 12:35 keys
drwxr-xr-x 4  911  911 4096 Jul 18 12:35 log
drwxrwxr-x 3  911  911 4096 Jul 18 12:35 nginx
drwxr-xr-x 2  911  911 4096 Jul 18 12:35 php
drwxrwxr-x 4  911  911 4096 Jul 18 13:21 www
`

docker inspect -f '{{ index .Config.Labels "build_version" }}' portal
Linuxserver.io version:- 70 Build-date:- September-05-2018-18:11:48-UTC

docker inspect -f '{{ index .Config.Labels "build_version" }}' linuxserver/heimdall
Linuxserver.io version:- 70 Build-date:- September-05-2018-18:11:48-UTC

**Comment by ovizii** [comment]
I now did a 
`chown -R ovi:ovi config/ `

id ovi results in 1000 

so now I use: 

`docker run -d --name=portal \
-v /home/ovi/docker/heimdall/config:/config \
-e PGID=1000 \
-e PUID=1000 \
--expose 80 \
--expose 443 \
--restart unless-stopped \
-e TZ=Europe/Berlin \
--label traefik.port=80 \
--label traefik.frontend.rule=Host:portal.mydomain.tld \
--label traefik.backend=portal \
--label traefik.enable=true \
--label 'traefik.frontend.auth.basic=ovi:$apr1$MYPASSWORDG5iDso0' \
linuxserver/heimdall
`
and still my heimdall instance is read-only.

**Comment by KodeStar** [comment]
Completely scrapping the container / image and local folder and starting from scratch should work, it's not the image as such that is having issues (as that hasn't changed in a while), it's that you set (or didn't set) the correct permissions and it's messed something up somewhere, you could probably run down the reason why with a lot of debugging, and if you do, let me know and I'll add it to the readme, but just redoing it is a lot quicker and easier.

**Comment by robflate** [comment]
I'm having the same problem. I tried scrapping the container, image and config folder and starting fresh but I still can't save changes. For example, if I set the Homepage Search toggle to On and click Save, the page refreshes and the toggle is switched off.

My Docker Compose is;

```
heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall
    volumes:
      - ./config/heimdall:/config
    environment:
      - 501
      - 20
      - Europe/London
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:mydomain.com"
      traefik.frontend.auth.basic: "mypassword"
    restart: unless-stopped
```

I had everything working fine before. Not sure what's different. Thanks.

**Comment by ovizii** [comment]
I didn't yet get around to scrapping and trying but I see what we both have in common is that we're using traefik with authentication. Could it be some headers are being filtered and this prevents saving?

**Comment by robflate** [comment]
Anyone else successfully using heimdall and traefik?

**Comment by yoyos** [comment]
Same. POST payload is lost if my server do a redirect to https before executing the ajax query. http/https should be chosen depending on how the website is displayed.

It worked when disabling my direction. But I need it :)
>  [entryPoints.http]
>   address = ":80"
> #    [entryPoints.http.redirect]
> #      entryPoint = "https"
> 
>   [entryPoints.https]
>   address = ":443"
>     [entryPoints.https.tls]

**Comment by KodeStar** [comment]
Then you need to run the underlying heimdall on https as well, if it's on https then the links should work as expected.

**Comment by yoyos** [comment]
that's not the problem, problem is http is hardcoded in some  POST<form> @KodeStar

**Comment by KodeStar** [comment]
I've just had a quick look and not found a single instance of it being hardcoded, so like I said, I'm pretty sure you have something configured incorrectly... if I run heimdall directly on https the form links are https and if I run it on http they are http.  I don't use traefik so I can't help with that I'm afraid, but i'm 99% sure it's not a problem with the app itself.  Happy to be shown where I'm wrong and I'll update it if I can.

**Comment by KodeStar** [comment]
here, you go, it's because it's behind a reverse proxy - https://biegal.ski/code/ssl-with-laravel-and-cloudflare-reverse-proxy

**Comment by KodeStar** [comment]
Just put out a new release 1.4.15, if you are running this release simply add `FORCE_HTTPS=true` to your .env

**Comment by yoyos** [comment]
@kodestar thanks you were right, http seems to come back because symfony thinks it's using http even if the user has https displayed because of the reverse proxy. So we have a few solutions:

- let heimdall chose if we use https or http by JavaScipt and not on server side
- have a config file to force https on server side
- force the developer to use https between it's reverse proxy and it's heimdall container.

I don't think the last one is the more flexible as all other apps I use never force developer like Heimdall. Using http between reverse proxy and container is a gain in performance and not a loss of security when you own different virtual private networks.

**Comment by yoyos** [comment]
@KodeStar  I added it as you said in my env but doesn't seem to work


```
version: '3'
services:
  web:
    image: linuxserver/heimdall:latest
    restart: always
    volumes:
      - /data/docker/heimdall/config:/config
    environment:
      TERM: xterm
      PGID: 33
      PUID: 33
      TZ: Europe/Brussels
      FORCE_HTTPS: "true"
    labels:
      - traefik.backend=heimdall
      - traefik.frontend.rule=Host:home.xxxx.com
      - traefik.protocol=http
      - traefik.port=80
      - traefik.frontend.entryPoints=http,https
    container_name: heimdall
    networks:
      - web
networks:
  web:
    external: true

```


![image](https://user-images.githubusercontent.com/1993859/46257911-66ab4500-c4c2-11e8-94f6-ae7d6dd9a36f.png)


Yes I pulled the last image build 76 :)
