### ISSUE TITLE
Ingress and heimdall https error

### ISSUE THREAD

**Issue by sylflo** [linuxserver/Heimdall#315]
I'm struggling to set Ingress and Heimdall together, I have differents software which are currently running with no problem in HTTPS (Seafile, plex, Sonarr, deluge ...)

But I can't make it happen with Heimdall, I think the problen is related to the fact the URL are hardcoded.
I have this error 
```
Mixed Content: The page at 'https://heimdall.daydreamnation.fr/' was loaded over HTTPS, but requested an insecure stylesheet 'http://heimdall.daydreamnation.fr/css/app.css'. This request has been blocked; the content must be served over HTTPS.
```
I saw this issue https://github.com/linuxserver/Heimdall/issues/268.

So I suppose because of the error I have in the console it means the redirect does not happen correctly but I try to go to `http://heimdall.daydreamnation.fr/css/app.css` it redirects me correctly to the HTTPS.

My ingress config file is like this
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.clusterissuer }}
  creationTimestamp: null
  labels:
    io.kompose.service: heimdall
  name: heimdall
spec:
  rules:
  - host: heimdall.{{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: heimdall
          servicePort: 80
  tls:
  - hosts:
    - heimdall.{{ .Values.domain_name }}
    secretName: heimdall-crt
status:
  loadBalancer: {}
```
