### ISSUE TITLE
domain name added by traefik

### ISSUE THREAD

**Issue by daviddoji** [linuxserver/Heimdall#350]
I'm running both heimdall and traefik plus a bunch of other services using docker-compose.

All services work fine, but heimdall is the only one with a warning sign and also the only in which I have to specify the port number.

Here is part of my docker-compose file:
`version=3

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    env_file:
      - .heimdall-env
    volumes:
      - ./heimdall/config:/config
    ports:
      - 7000:80
      - 7001:443
    labels:
      - traefik.backend=heimdall
      - traefik.fronted.rule=Host:start.mydomain.com
      - traefik.port=7001
      - traefik.enable=true
      - traefik.protocol=https
`
I have to specify the ports, otherwise, I can't get to the subdomain. With other services, such as calibre-web, medusa, radicale, bitwarden, etc. that is not neccesary because traefik takes care of them.

This is the .env file for heimdall:

`COMPOSE_PROJECT_NAME=homeserver

PYTHONBUFFERED=true
PUID=1000
PGID=1000
TZ=Europe/Berlin
`

What I have realized is that traefik gives a weird name to the subdomain for heimdall:
`{

      "Domain": {
        "Main": "heimdall.homeserver.mydomain.com",`

whereas for other services running also under traefik, the subdomain's name is the one specified on the docker-compose.yaml.

**Comment by mabushey** [comment]
Hi @daviddoji. @KodeStar just made a change to make Heimdall reverse proxy friendly. I have it running under traefik w/o any issues that I can see; It didn't work yesterday. Here's my config with no exposed ports, and SSL via traefik:
```
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./docker-heimdall:/config
    labels:
      - traefik.frontend.rule=Host:heim.example.com
      - traefik.port=80
      - traefik.docker.network=web
    networks:
      - web
```
