### ISSUE TITLE
Deploy Heimdall on Kubernetes with Nginx custom config

### ISSUE THREAD

**Issue by rdrgporto** [linuxserver/Heimdall#419]
Hi, everyone:

I'm trying to deploy **Heimdall on Kubernetes**. I have modified **NGINX configuration** and I have added **TLS certificates**.

An example of my **Kubernetes manifests**

**nginx-configmap.yml**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: heimdall-nginx-config
  namespace: kube-system
  labels:
    k8s-app: heimdall
data:
  default: |-
    ## Version 2018/03/06 - Changelog: https://github.com/linuxserver/docker-heimdall/commits/master/root/defaults/default

    server {
            listen 80 default_server;
            listen 443 ssl;
            root /var/www/localhost/heimdall/public;
            index index.php index.html index.htm;
            server_name _;

            ssl_certificate /certificates/heimdall.pem;
            ssl_certificate_key /certificates/heimdall.key;

            client_max_body_size 0;
            error_page 599 = @noauth;
            location / {
                    if (!-f /config/nginx/.htpasswd) {
                            return 599;
                    }
                    auth_basic "Restricted";
                    auth_basic_user_file /config/nginx/.htpasswd;
                    try_files $uri $uri/ /index.php?$args;
            }
            location @noauth {
                    try_files $uri $uri/ /index.php?$args;
            }
            location ~ \.php$ {
                    fastcgi_split_path_info ^(.+\.php)(/.+)$;
                    # With php5-cgi alone:
                    fastcgi_pass 127.0.0.1:9000;
                    # With php5-fpm:
                    #fastcgi_pass unix:/var/run/php5-fpm.sock;
                    fastcgi_index index.php;
                    include /etc/nginx/fastcgi_params;
            }
    }
```

**heimdall-deploy.yml**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: kube-system
  labels:
    k8s-app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heimdall
  template:
    metadata:
      labels:
        k8s-app: heimdall
    spec:
      containers:
      - name: heimdall
        image: linuxserver/heimdall:2.2.2-ls65
        ports:
        - name: https
          containerPort: 443
        resources:
         requests:
          cpu: 500m
          memory: 250Mi
         limits:
          cpu: 500m
          memory: 250Mi
        volumeMounts:
        - name: storage
          mountPath: /config/www
        - name: nginx-config
          mountPath: /config/nginx/site-confs/default
          subPath: default
        - name: tls
          mountPath: /certificates
      volumes:
      - name: storage
        hostPath:
         path: /var/heimdall
      - name: nginx-config
        configMap:
         name: heimdall-nginx-config
      - name: tls
        secret:
         secretName: heimdall-tls
      nodeSelector:
        storage: node-03
```

**Heimdall** shows the following message:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
usermod: no changes
User uid:    911
User gid:    911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
chown: changing ownership of '/config/nginx/site-confs/default': Read-only file system
chmod: changing permissions of '/config/nginx/site-confs/default': Read-only file system
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
...................................................................................+++++
......................................................+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
New container detected, installing Heimdall
Setting permissions
chown: changing ownership of '/config/nginx/site-confs/default': Read-only file system
[cont-init.d] 50-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Thanks in advance,

Rodrigo 🖖
