### ISSUE TITLE
Reverse Proxy with NGINX and Let's Encrypt

### ISSUE THREAD

**Issue by SethGower** [linuxserver/Heimdall#533]
Hello, I am trying to secure this with let's encrypt, and am having some issues with the nginx config. If I go to just `heimdall.example.com` (domain name changed), I get this
![image](https://user-images.githubusercontent.com/19225089/102790013-e3ac8880-4372-11eb-8b2f-fc6193f1ae3e.png)

If I add the port (in docker I configured `6080` and `6043` for `http` and `https` respectively) for `http`, it loads properly. 

The SSL version does the same thing. Am I doing something incorrectly with nginx?

My `nginx` config is below:
```nginx
server {
    server_name heimdall.example.com;
    location / {
        proxy_pass http://localhost:6080/;
        try_files $uri $uri/ /index.php?$query_string;
    }

    listen 80; # managed by Certbot

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/heimdall.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/heimdall.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

My docker config for heimdall:
```yaml
    heimdall:
        image: ghcr.io/linuxserver/heimdall
        container_name: heimdall
        volumes:
            - /etc/Heimdall:/config
        environment:
            - TZ=America/New_York
            - PUID=1000
            - PGID=1000
        ports:
            - 6080:80
            - 6043:443
        restart: unless-stopped
```
