### ISSUE TITLE
Enhancement : way to integrate apps based on docker compose labels

### ISSUE THREAD

**Issue by lunarok** [linuxserver/Heimdall#559]
Hi,

In a world with things like traefik+authelia+cf-companion, the perfection will be to have a portal that allow to integrate by anyway a dynamic list of apps, those being pick up from the docker labels.
Exemple, adding a new container, with just exposing to traefik, we have the subdomain create, subdomain protected by sso with nothing to do. If it could go to the step of being added in heimdall ...

**Comment by Bockiii** [comment]
I came here to post the same exact feature request :). so +1 for this

**Comment by holblin** [comment]
Also interested 👍 
I personally use traefik + traefik-auth-forwarder + let's encrypt (through traefik dynamic configuration)

**Comment by francis-io** [comment]
I also came here to request the same thing. 

My initial idea was to have labels be read on a Heimdall container. The label path can be used to get the explicit name of each entry.

```
services:
  heimdall:
    image: linuxserver/heimdall:latest
    labels:
      - "application.mySonarr.applicationType=sonarr"
      - "application.mySonarr.url=https://sonarr.mydomain.com"
      - "application.LivingRoom:odi.applicationType=kodi"
      - "application.LivingRoomKodi.url=https://kodi.mydomain.com"
```

The other option is to label the other containers. 

```
services:
  sonarr:
    image: linuxserver/sonarr
    labels:
      - "application.heimdall.applicationType=sonarr"
      - "application.heimdall.url=https://sonarr.mydomain.com"
```

I guess this all comes down to the access you want to give Heimdall. Can a container read its own labels? I assume by default it can't read other container labels. I wouldn't really want to expose the docker socket to my heindall container unless I really needed to. Mounting as read-only is a way to limit risk here somewhat.

I could also see labels on the heimdall container being used to set things in system settings and for users. 

The big difficulty I see is managing button layout. I guess that could be controlled by an "order" label. `application.heimdall.layoutOrder=2`. Any conflicting order labels could then go based off of alphabetical order.

The big missing feature for me personally with heimdall is the ability to work without a local state at all. I think it's perfectly suited to doing this. As far as I can tell, it does not keep any state, just a config file. 

I'm tempted to experiment with adding a new entrypoint script to the Heimdall container image to render out a config file based on labels. It seems like it should be easy enough. You can just curl a mounted docker socket as explained here https://stackoverflow.com/a/39714741
