### ISSUE TITLE
Nextcloud Missing

### ISSUE THREAD

**Issue by ndrwstn** [linuxserver/Heimdall#560]
Nextcloud isn't showing in the app list, even after updating app list (several times) and restarting docker container.

This can be merged into #340 but I can't reopen that issue.

**Comment by Erriez** [comment]
I use Nextcloud from the app list in the latest heimdall v2.2.2 without issues on AMD64:

```
$ docker run -it --name heimdall --rm -p 8080:80 -e PUID=1000 -e PGID=1000 -e TZ=Europe/Amsterdam -v ${PWD}/volumes/heimdall/config:/config ghcr.io/linuxserver/heimdall

$ docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
ghcr.io/linuxserver/heimdall   latest              e83812ff9cf2        6 days ago          88.6MB
```

![Screenshot from 2021-02-27 11-35-06](https://user-images.githubusercontent.com/8849873/109384857-e9cd6100-78ef-11eb-96cb-a2566adedb1c.png)

**Comment by ndrwstn** [comment]
Perhaps it's an ARM64 issue then?

**Comment by Erriez** [comment]
@ndrwstn I've heimdall version 2.2.2 up and running on my Raspberry Pi 4 with Ubuntu 20.04 64-bit and displays Nextcloud correctly.

docker-compose.yaml:
```yaml
version: '3'

services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall:version-2.2.2
    container_name: heimdall
    restart: always
    # ports:
    #   - :443
    environment:
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
      - TZ=${TZ}
    volumes:
      - ${VOLUME_DIR}/heimdall/config:/config

  # Reverse proxy with SSL
  swag:
    # docker exec -it swag htpasswd /config/nginx/.htpasswd <username>
    #   -c  Create a new file.
    image: ghcr.io/linuxserver/swag:version-1.12.0
    container_name: swag
    restart: always
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$DOCKER_UID
      - PGID=$DOCKER_GID
      - EMAIL=${SWAG_EMAIL}
      - URL=${ROOT_DOMAIN}
      - SUBDOMAINS=${SWAG_SUBDOMAINS}
      - VALIDATION=${SWAG_VALIDATION}
      - DNSPLUGIN=${SWAG_DNSPLUGIN}
      - PROPAGATION=${SWAG_PROPAGATION}
      - ONLY_SUBDOMAINS=${SWAG_ONLY_SUBDOMAINS}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_DIR}/swag/config:/config
```
