### ISSUE TITLE
Dashboard fails to completely load

### ISSUE THREAD

**Issue by lenaxia** [linuxserver/Heimdall#607]
When I load up my dashboard it takes a substantial time to load (20+ seconds), and eventually fails to load some of the icons, and sometimes the background. After giving it some time and refreshing, it will load everything. 

Currently the dashboard is behind Traefik and Authelia, however this behavior exists with or without a reverse proxy

```
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=T{TZ}
    volumes:
      - $DOCKERDIR/heimdall:/config
    ports:
      - 3380:80
    #  - 3443:443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.heimdall-rtr.entrypoints=https"
      - "traefik.http.routers.heimdall-rtr.rule=Host(`$DOMAINMIKEGOESONLINE`)"
      - "traefik.http.routers.heimdall-rtr.tls=true"
      - "traefik.http.routers.heimdall-rtr.priority=90"
      ## Middlewares
      - "traefik.http.routers.heimdall-rtr.middlewares=chain-authelia-mikegoesonline@file"
      ## HTTP Services
      - "traefik.http.routers.heimdall-rtr.service=heimdall-svc"
      - "traefik.http.services.heimdall-svc.loadbalancer.server.port=80"
    networks:
      - t2_proxy


networks:
  t2_proxy:
    external: true
```
