### ISSUE TITLE
Search engine 500

### ISSUE THREAD

**Issue by martadinata666** [linuxserver/Heimdall#764]
The search engine throw exception:

/var/www/html/app/Http/Controllers/SearchController.php:19
```
            $query = $request->input('q');
            $provider = Search::providerDetails($requestprovider);
            if($provider->type == 'standard') {
                return redirect($provider->url.'?'.$provider->var.'='.urlencode($query)); /*this line is highlighted*/
            } elseif($provider->type == 'external') {
                $class = new $provider->class;
                //print_r($provider);
                return $class->getResults($query, $provider);
            }
```

searchproviders.yaml
```
whoogle:
   id: whoogle
   url: https://192.168.0.2:5050/search
   name: Whoogle
   method: get
   target: _blank
   query: q

google:
   id: google
   url: https://www.google.com/search
   name: Google
   method: get
   target: _blank
   query: q

bing:
   id: bing
   url: https://www.bing.com/search
   name: Bing
   method: get
   target: _blank
   query: q

ddg:
   id: ddg
   url: https://duckduckgo.com/
   name: DuckDuckGo
   method: get
   target: _blank
   query: q

startpage:
   id: startpage
   url: https://www.startpage.com/do/dsearch
   name: Startpage
   method: get
   target: _blank
   query: query

```

the URL
```
https://192.168.0.2/search?provider=google&q=ubuntu+22.04+release+date
```

It just default, any clue?

**Comment by martadinata666** [comment]
replace query with var
```
google:
   id: google
   url: https://www.google.com/search
   name: Google
   method: get
   target: _blank
   query: q

```

```
google:
   id: google
   url: https://www.google.com/search
   name: Google
   method: get
   target: _blank
   var: q
```
