### ISSUE TITLE
Given a configured keycloak server, is it possible to use this site along with oidc to support multiple users?

### ISSUE THREAD

**Issue by lknite** [linuxserver/Heimdall#872]
I've noticed there is a heimdall oauth2 server so I'm betting there is already an integration available.  Maybe?

I've looked into an authenticating proxy:
[https://github.com/oauth2-proxy/oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy)

Which has an example of being an interface in front of the kubernetes dashboard, which knows how to accept the token passed along by the oauth2-proxy.  Is it possible heimdall apps also knows how to work with such a token?
[https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/](https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/)

**Comment by lknite** [comment]
k, got this working yesterday, have got heimdall setup behind an oauth2-proxy and have set it up to pass along a bearer token

Can heimdall use this token to allow different users access to their own heimdall desktop?

**Comment by lknite** [comment]
Updated my clusters and redeployed this again.  So far this is my favorite dashboard-type app.  Hoping it might be possible to support multiple users / oidc.

**Comment by lknite** [comment]
On the heimdall side, my oauth2-proxy configuration in the annotation section:
```
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.vc-prod.k.home.net/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.vc-prod.k.home.net/oauth2/start?rd=https%3A%2F%2Fheimdall.vc-prod.k.home.net"
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
```
