### ISSUE TITLE
419 Page Expired doing any POST requests

### ISSUE THREAD

**Issue by karan** [linuxserver/Heimdall#873]
------------------------------

## Expected Behavior
I am able to edit items or add new ones.

## Current Behavior
As of some time in the last few weeks, I get "419 Page Expired" when trying to add or edit an item. This also happens when trying to delete items, or delete items in trash. Basically anything that makes a POST request.

## Steps to Reproduce
1. Try to add a new item
2. Click Save

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** Docker linuxserver/heimdall:v2.4.13-ls177

There aren't really any useful logs anywhere for me to debug.

## Command used to create docker container (run/create/compose/screenshot)
Standard compose service. This started happening some time in the last few weeks (I didn't change my config).

```
  heimdall:
    # https://github.com/linuxserver/docker-heimdall/releases
    image: linuxserver/heimdall:v2.4.13-ls177
    container_name: heimdall
    networks:
      - internal
    environment:
      PGID: 1000
      PUID: 1000
      TZ: "America/Los_Angeles"
      APP_NAME: "placeholder"
    volumes:
      - /home/placeholder/placeholder/heimdall/config:/config
    ports:
      - 8199:80
    restart: unless-stopped
```

User 1000 is my main user on the server. I've always used this. This user has permissions on the config directory.

## Docker logs

```
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
Setting permissions
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
