### ISSUE TITLE
Custom Search Engine Setting

### ISSUE THREAD

**Issue by tucker19** [linuxserver/Heimdall#885]
Is it possible to get a option to out in a custom search engine in?

**Comment by Dictynna-PHA** [comment]
You can edit the searchproviders.yaml file to use any provider to pin as a homepage search.

**Comment by ma651851384** [comment]
@tucker19 I tried it out to add an additional search provider, as mentioned from @Dictynna-PHA.

Edit the file `./config/www/searchproviders.yaml`. In my case I have added the search engine "metager.de" at the end of the file:

```
metager:
   id: metager
   url: https://metager.de/meta/meta.ger3
   name: metager
   method: get
   target: _blank
   query: eingabe
```

The help website from that search engine contains the needed information like the URL, which has to be used (german):
https://metager.de/hilfe/funktionen#selist

Additionally, I changed the default search provide to metager. This is possible via the heimdall settings.
